version: '3'
      
volumes:
  db:
  cache:
  data01:
    driver: local

services:
  postgresql:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - elastic

  api:
    depends_on:
      - 'postgresql'
    build: .
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - cache:/cache
      - "/etc/localtime:/etc/localtime"
    ports:
      - "3000:3000"
    networks:
      - elastic
    env_file:
      - '.env.docker'
  
networks:
  elastic:
    driver: bridge