apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: fitbod-api
          imagePullPolicy: Never
          command: ['rails']
          args: ['db:migrate']
          env:                     # Environment variables passed to the container
          - name: RAILS_ENV
            value: production