development:
  adapter: postgresql
  database: fitbod_development
  timeout: 5000
  username: postgres
  password: postgres
  pool: 20
  host: postgres
  port: 5432

test:
  adapter: postgresql
  database: fitbod_test
  timeout: 5000
  username: postgres
  password: postgres
  host: postgres
  port: 5432

production:
  adapter: postgresql
  database: fitbod_production
  timeout: 5000
  username: postgres
  password: postgres
  pool: 20
  host: postgres
  port: 5432